version: '3.9'

services:
  safety-system-db:
    image: postgres
    env_file: ./local/db.env
    restart: always
    ports:
      - 5432:5432

  safety-system-api:
    build:
      context: ../safety-system-api
      dockerfile: Dockerfile.local
    env_file:
      - ./local/api.env
    ports:
      - 4000:80
    depends_on:
      - safety-system-db
    resters: always